# Generated by Django 6.0.5 on 2026-05-29 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0002_remove_transaction_payment_method_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='financialaccount',
            name='payment_due_date',
        ),
        migrations.AddField(
            model_name='financialaccount',
            name='payment_due_day',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financialaccount',
            name='statement_closing_day',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
