# Generated by Django 6.0.5 on 2026-05-31 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0003_remove_financialaccount_payment_due_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialaccount',
            name='used_credit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
